-- NOTE: This file is auto generated by ./sql-generator

-- CategoryRepository.getByAssetId
select
  "asset_categories".*
from
  "asset_categories"
where
  "asset_categories"."assetId" = $1
order by
  "asset_categories"."confidence" desc

-- CategoryRepository.getDistinctCategories
select
  "asset_categories"."categoryName",
  count("asset_categories"."id")::int as "count"
from
  "asset_categories"
  inner join "asset" on "asset"."id" = "asset_categories"."assetId"
where
  "asset"."ownerId" = $1
  and "asset"."deletedAt" is null
  and "asset"."visibility" != $2
group by
  "asset_categories"."categoryName"
order by
  "count" desc

-- CategoryRepository.upsert
begin
delete from "asset_categories"
where
  "assetId" = $1
insert into
  "asset_categories" ("assetId", "categoryName", "confidence")
values
  ($1, $2, $3)
rollback

-- CategoryRepository.getTopCategoriesWithAsset
with
  "top_cats" as (
    select
      "asset_categories"."categoryName"
    from
      "asset_categories"
      inner join "asset" on "asset"."id" = "asset_categories"."assetId"
    where
      "asset"."ownerId" = $1
      and "asset"."deletedAt" is null
      and "asset"."visibility" = $2
    group by
      "asset_categories"."categoryName"
    having
      count("asset_categories"."id") >= $3
  )
select distinct
  on ("asset_categories"."categoryName") "asset_categories"."assetId" as "data",
  "asset_categories"."categoryName" as "value"
from
  "asset_categories"
  inner join "asset" on "asset"."id" = "asset_categories"."assetId"
  inner join "top_cats" on "top_cats"."categoryName" = "asset_categories"."categoryName"
where
  "asset"."ownerId" = $4
  and "asset"."deletedAt" is null
  and "asset"."visibility" = $5
  and "asset"."type" = $6
order by
  "asset_categories"."categoryName",
  "asset_categories"."confidence" desc
